### ISSUE TITLE
Expo compability

### ISSUE THREAD

**Issue by hasanfd** [mentrena/react-native-redrag-and-drop#1]
Thanks for the awesome job!
Is this component compatible with the expo?

**Comment by mentrena** [comment]
It is, you just need to make sure to install `react-native-reanimated` and `react-native-gesture-handler` following the [Expo instructions](https://docs.expo.dev/versions/latest/sdk/reanimated/):
```
expo install react-native-reanimated
expo install react-native-gesture-handler
```

Then just install the library:
```
expo install react-native-redrag-and-drop
```

**Comment by hasanfd** [comment]
Thanks @mentrena
